// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcVYpHYe5WKf79M2wMgEOFYRzsx_Qipt4',
    appId: '1:209408222799:web:3890de509a35705bbe2c3a',
    messagingSenderId: '209408222799',
    projectId: 'flutter-todo-c3b05',
    authDomain: 'flutter-todo-c3b05.firebaseapp.com',
    storageBucket: 'flutter-todo-c3b05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wfbta7ECbA8blQrXIA7u6z0KWJxFl2c',
    appId: '1:209408222799:android:db64ab4dd84b147bbe2c3a',
    messagingSenderId: '209408222799',
    projectId: 'flutter-todo-c3b05',
    storageBucket: 'flutter-todo-c3b05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVSzb0XO3dNtqx3yaEf2q2RamAc7NJWA',
    appId: '1:209408222799:ios:f4ce088e71344203be2c3a',
    messagingSenderId: '209408222799',
    projectId: 'flutter-todo-c3b05',
    storageBucket: 'flutter-todo-c3b05.appspot.com',
    iosClientId: '209408222799-li2d1v7tlk3iencbt9i3at89nv8dc74l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNVSzb0XO3dNtqx3yaEf2q2RamAc7NJWA',
    appId: '1:209408222799:ios:f4ce088e71344203be2c3a',
    messagingSenderId: '209408222799',
    projectId: 'flutter-todo-c3b05',
    storageBucket: 'flutter-todo-c3b05.appspot.com',
    iosClientId: '209408222799-li2d1v7tlk3iencbt9i3at89nv8dc74l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
